//配列
const AC_ChampionImageTag = ['<center><img id=0 onclick="reimage(0);" src="image/icon/ico_Ahri.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=1 onclick="reimage(1);" src="image/icon/ico_Akali.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=2 onclick="reimage(2);" src="image/icon/ico_Akshan.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=3 onclick="reimage(3);" src="image/icon/ico_Alistar.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=4 onclick="reimage(4);" src="image/icon/ico_Amumu.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=5 onclick="reimage(5);" src="image/icon/ico_Anivia.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=6 onclick="reimage(6);" src="image/icon/ico_Annie.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=7 onclick="reimage(7);" src="image/icon/ico_Aphelios.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=8 onclick="reimage(8);" src="image/icon/ico_Ashe.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=9 onclick="reimage(9);" src="image/icon/ico_AurelionSol.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=10 onclick="reimage(10);" src="image/icon/ico_Azir.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=11 onclick="reimage(11);" src="image/icon/ico_Bard.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=12 onclick="reimage(12);" src="image/icon/ico_BelVeth.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=13 onclick="reimage(13);" src="image/icon/ico_Blitzcrank.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=14 onclick="reimage(14);" src="image/icon/ico_Brand.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=15 onclick="reimage(15);" src="image/icon/ico_Braum.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=16 onclick="reimage(16);" src="image/icon/ico_Caitlyn.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=17 onclick="reimage(17);" src="image/icon/ico_Camille.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=18 onclick="reimage(18);" src="image/icon/ico_Cassiopeia.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=19 onclick="reimage(19);" src="image/icon/ico_Chogath.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=20 onclick="reimage(20);" src="image/icon/ico_Corki.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=21 onclick="reimage(21);" src="image/icon/ico_Darius.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=22 onclick="reimage(22);" src="image/icon/ico_Diana.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=23 onclick="reimage(23);" src="image/icon/ico_Draven.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=24 onclick="reimage(24);" src="image/icon/ico_Drmundo.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=25 onclick="reimage(25);" src="image/icon/ico_Ekko.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=26 onclick="reimage(26);" src="image/icon/ico_Elise.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=27 onclick="reimage(27);" src="image/icon/ico_Evelynn.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=28 onclick="reimage(28);" src="image/icon/ico_Ezreal.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=29 onclick="reimage(29);" src="image/icon/ico_Fiddlesticks.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=30 onclick="reimage(30);" src="image/icon/ico_Fiora.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=31 onclick="reimage(31);" src="image/icon/ico_Fizz.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=32 onclick="reimage(32);" src="image/icon/ico_Galio.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=33 onclick="reimage(33);" src="image/icon/ico_Gangplank.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=34 onclick="reimage(34);" src="image/icon/ico_Garen.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=35 onclick="reimage(35);" src="image/icon/ico_Gnar.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=36 onclick="reimage(36);" src="image/icon/ico_Gragas.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=37 onclick="reimage(37);" src="image/icon/ico_Graves.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=38 onclick="reimage(38);" src="image/icon/ico_Gwen.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=39 onclick="reimage(39);" src="image/icon/ico_Hecarim.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=40 onclick="reimage(40);" src="image/icon/ico_Heimerdinger.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=41 onclick="reimage(41);" src="image/icon/ico_Illaoi.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=42 onclick="reimage(42);" src="image/icon/ico_Irelia.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=43 onclick="reimage(43);" src="image/icon/ico_Ivern.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=44 onclick="reimage(44);" src="image/icon/ico_Janna.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=45 onclick="reimage(45);" src="image/icon/ico_JarvanIV.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=46 onclick="reimage(46);" src="image/icon/ico_Jax.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=47 onclick="reimage(47);" src="image/icon/ico_Jayce.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=48 onclick="reimage(48);" src="image/icon/ico_Jhin.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=49 onclick="reimage(49);" src="image/icon/ico_Jinx.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=50 onclick="reimage(50);" src="image/icon/ico_Kaisa.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=51 onclick="reimage(51);" src="image/icon/ico_Kalista.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=52 onclick="reimage(52);" src="image/icon/ico_Karma.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=53 onclick="reimage(53);" src="image/icon/ico_Karthus.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=54 onclick="reimage(54);" src="image/icon/ico_Kassadin.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=55 onclick="reimage(55);" src="image/icon/ico_Katarina.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=56 onclick="reimage(56);" src="image/icon/ico_Kayle.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=57 onclick="reimage(57);" src="image/icon/ico_Kayn.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=58 onclick="reimage(58);" src="image/icon/ico_Kennen.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=59 onclick="reimage(59);" src="image/icon/ico_KhaZix.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=60 onclick="reimage(60);" src="image/icon/ico_Kindred.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=61 onclick="reimage(61);" src="image/icon/ico_Kled.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=62 onclick="reimage(62);" src="image/icon/ico_KogMaw.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=63 onclick="reimage(63);" src="image/icon/ico_leblanc.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=64 onclick="reimage(64);" src="image/icon/ico_LeeSin.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=65 onclick="reimage(65);" src="image/icon/ico_Leona.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=66 onclick="reimage(66);" src="image/icon/ico_Lillia.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=67 onclick="reimage(67);" src="image/icon/ico_Lissandra.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=68 onclick="reimage(68);" src="image/icon/ico_Lucian.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=69 onclick="reimage(69);" src="image/icon/ico_Lulu.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=70 onclick="reimage(70);" src="image/icon/ico_Lux.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=71 onclick="reimage(71);" src="image/icon/ico_Malphite.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=72 onclick="reimage(72);" src="image/icon/ico_Malzahar.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=73 onclick="reimage(73);" src="image/icon/ico_Maokai.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=74 onclick="reimage(74);" src="image/icon/ico_Masteryi.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=75 onclick="reimage(75);" src="image/icon/ico_MissFortune.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=76 onclick="reimage(76);" src="image/icon/ico_MonkeyKing.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=77 onclick="reimage(77);" src="image/icon/ico_Mordekaiser.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=78 onclick="reimage(78);" src="image/icon/ico_Morgana.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=79 onclick="reimage(79);" src="image/icon/ico_Nami.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=80 onclick="reimage(80);" src="image/icon/ico_Nasus.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=81 onclick="reimage(81);" src="image/icon/ico_Nautilus.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=82 onclick="reimage(82);" src="image/icon/ico_Neeko.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=83 onclick="reimage(83);" src="image/icon/ico_Nidalee.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=84 onclick="reimage(84);" src="image/icon/ico_Nilah.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=85 onclick="reimage(85);" src="image/icon/ico_Nocturne.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=86 onclick="reimage(86);" src="image/icon/ico_Nunu.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=87 onclick="reimage(87);" src="image/icon/ico_Olaf.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=88 onclick="reimage(88);" src="image/icon/ico_Orianna.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=89 onclick="reimage(89);" src="image/icon/ico_Ornn.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=90 onclick="reimage(90);" src="image/icon/ico_Pantheon.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=91 onclick="reimage(91);" src="image/icon/ico_Poppy.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=92 onclick="reimage(92);" src="image/icon/ico_Pyke.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=93 onclick="reimage(93);" src="image/icon/ico_Qiyana.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=94 onclick="reimage(94);" src="image/icon/ico_Quinn.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=95 onclick="reimage(95);" src="image/icon/ico_Rakan.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=96 onclick="reimage(96);" src="image/icon/ico_Rammus.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=97 onclick="reimage(97);" src="image/icon/ico_RekSai.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=98 onclick="reimage(98);" src="image/icon/ico_Rell.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=99 onclick="reimage(99);" src="image/icon/ico_Renekton.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=100 onclick="reimage(100);" src="image/icon/ico_Rengar.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=101 onclick="reimage(101);" src="image/icon/ico_Riven.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=102 onclick="reimage(102);" src="image/icon/ico_Rumble.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=103 onclick="reimage(103);" src="image/icon/ico_Ryze.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=104 onclick="reimage(104);" src="image/icon/ico_Samira.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=105 onclick="reimage(105);" src="image/icon/ico_Sejuani.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=106 onclick="reimage(106);" src="image/icon/ico_Senna.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=107 onclick="reimage(107);" src="image/icon/ico_Seraphine.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=108 onclick="reimage(108);" src="image/icon/ico_Sett.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=109 onclick="reimage(109);" src="image/icon/ico_Shaco.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=110 onclick="reimage(110);" src="image/icon/ico_Shen.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=111 onclick="reimage(111);" src="image/icon/ico_Shyvana.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=112 onclick="reimage(112);" src="image/icon/ico_Singed.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=113 onclick="reimage(113);" src="image/icon/ico_Sion.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=114 onclick="reimage(114);" src="image/icon/ico_Sivir.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=115 onclick="reimage(115);" src="image/icon/ico_Skarner.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=116 onclick="reimage(116);" src="image/icon/ico_Sona.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=117 onclick="reimage(117);" src="image/icon/ico_Soraka.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=118 onclick="reimage(118);" src="image/icon/ico_Swain.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=119 onclick="reimage(119);" src="image/icon/ico_Sylas.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=120 onclick="reimage(120);" src="image/icon/ico_Syndra.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=121 onclick="reimage(121);" src="image/icon/ico_TahmKench.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=122 onclick="reimage(122);" src="image/icon/ico_Taliyah.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=123 onclick="reimage(123);" src="image/icon/ico_Talon.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=124 onclick="reimage(124);" src="image/icon/ico_Taric.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=125 onclick="reimage(125);" src="image/icon/ico_Teemo.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=126 onclick="reimage(126);" src="image/icon/ico_Thresh.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=127 onclick="reimage(127);" src="image/icon/ico_Tristana.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=128 onclick="reimage(128);" src="image/icon/ico_Trundle.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=129 onclick="reimage(129);" src="image/icon/ico_Tryndamere.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=130 onclick="reimage(130);" src="image/icon/ico_Twistedfate.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=131 onclick="reimage(131);" src="image/icon/ico_Twitch.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=132 onclick="reimage(132);" src="image/icon/ico_Udyr.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=133 onclick="reimage(133);" src="image/icon/ico_Urgot.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=134 onclick="reimage(134);" src="image/icon/ico_Varus.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=135 onclick="reimage(135);" src="image/icon/ico_Vayne.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=136 onclick="reimage(136);" src="image/icon/ico_Veigar.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=137 onclick="reimage(137);" src="image/icon/ico_VelKoz.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=138 onclick="reimage(138);" src="image/icon/ico_Vex.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=139 onclick="reimage(139);" src="image/icon/ico_Vi.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=140 onclick="reimage(140);" src="image/icon/ico_Viego.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=141 onclick="reimage(141);" src="image/icon/ico_Viktor.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=142 onclick="reimage(142);" src="image/icon/ico_Vladimir.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=143 onclick="reimage(143);" src="image/icon/ico_Volibear.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=144 onclick="reimage(144);" src="image/icon/ico_Warwick.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=145 onclick="reimage(145);" src="image/icon/ico_Xayah.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=146 onclick="reimage(146);" src="image/icon/ico_Xerath.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=147 onclick="reimage(147);" src="image/icon/ico_Xinzhao.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=148 onclick="reimage(148);" src="image/icon/ico_Yasuo.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=149 onclick="reimage(149);" src="image/icon/ico_Yone.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=150 onclick="reimage(150);" src="image/icon/ico_Yorick.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=151 onclick="reimage(151);" src="image/icon/ico_Yuumi.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=152 onclick="reimage(152);" src="image/icon/ico_Zac.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=153 onclick="reimage(153);" src="image/icon/ico_Zed.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=154 onclick="reimage(154);" src="image/icon/ico_Zeri.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=155 onclick="reimage(155);" src="image/icon/ico_Ziggs.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=156 onclick="reimage(156);" src="image/icon/ico_Zilean.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=157 onclick="reimage(157);" src="image/icon/ico_Zoe.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=158 onclick="reimage(158);" src="image/icon/ico_Zyra.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=159 onclick="reimage(159);" src="image/icon/ico_RenataGlasc.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>', 
                             '<center><img id=160 onclick="reimage(160);" src="image/icon/ico_Aatrox.jpg" class="img-thumbnail" alt="..." width="100" height="100"></center>'
                             ];

const AC_ChampionSrc = ['image/icon/ico_Ahri.jpg', 
                        'image/icon/ico_Akali.jpg', 
                        'image/icon/ico_Akshan.jpg', 
                        'image/icon/ico_Alistar.jpg', 
                        'image/icon/ico_Amumu.jpg', 
                        'image/icon/ico_Anivia.jpg', 
                        'image/icon/ico_Annie.jpg', 
                        'image/icon/ico_Aphelios.jpg', 
                        'image/icon/ico_Ashe.jpg', 
                        'image/icon/ico_AurelionSol.jpg', 
                        'image/icon/ico_Azir.jpg', 
                        'image/icon/ico_Bard.jpg', 
                        'image/icon/ico_BelVeth.jpg', 
                        'image/icon/ico_Blitzcrank.jpg', 
                        'image/icon/ico_Brand.jpg', 
                        'image/icon/ico_Braum.jpg', 
                        'image/icon/ico_Caitlyn.jpg', 
                        'image/icon/ico_Camille.jpg', 
                        'image/icon/ico_Cassiopeia.jpg', 
                        'image/icon/ico_Chogath.jpg', 
                        'image/icon/ico_Corki.jpg', 
                        'image/icon/ico_Darius.jpg', 
                        'image/icon/ico_Diana.jpg', 
                        'image/icon/ico_Draven.jpg', 
                        'image/icon/ico_Drmundo.jpg', 
                        'image/icon/ico_Ekko.jpg', 
                        'image/icon/ico_Elise.jpg', 
                        'image/icon/ico_Evelynn.jpg', 
                        'image/icon/ico_Ezreal.jpg', 
                        'image/icon/ico_Fiddlesticks.jpg', 
                        'image/icon/ico_Fiora.jpg', 
                        'image/icon/ico_Fizz.jpg', 
                        'image/icon/ico_Galio.jpg', 
                        'image/icon/ico_Gangplank.jpg', 
                        'image/icon/ico_Garen.jpg', 
                        'image/icon/ico_Gnar.jpg', 
                        'image/icon/ico_Gragas.jpg', 
                        'image/icon/ico_Graves.jpg', 
                        'image/icon/ico_Gwen.jpg', 
                        'image/icon/ico_Hecarim.jpg', 
                        'image/icon/ico_Heimerdinger.jpg', 
                        'image/icon/ico_Illaoi.jpg', 
                        'image/icon/ico_Irelia.jpg', 
                        'image/icon/ico_Ivern.jpg', 
                        'image/icon/ico_Janna.jpg', 
                        'image/icon/ico_JarvanIV.jpg', 
                        'image/icon/ico_Jax.jpg', 
                        'image/icon/ico_Jayce.jpg', 
                        'image/icon/ico_Jhin.jpg', 
                        'image/icon/ico_Jinx.jpg', 
                        'image/icon/ico_Kaisa.jpg', 
                        'image/icon/ico_Kalista.jpg', 
                        'image/icon/ico_Karma.jpg', 
                        'image/icon/ico_Karthus.jpg', 
                        'image/icon/ico_Kassadin.jpg', 
                        'image/icon/ico_Katarina.jpg', 
                        'image/icon/ico_Kayle.jpg', 
                        'image/icon/ico_Kayn.jpg', 
                        'image/icon/ico_Kennen.jpg', 
                        'image/icon/ico_KhaZix.jpg', 
                        'image/icon/ico_Kindred.jpg', 
                        'image/icon/ico_Kled.jpg', 
                        'image/icon/ico_KogMaw.jpg', 
                        'image/icon/ico_leblanc.jpg', 
                        'image/icon/ico_LeeSin.jpg', 
                        'image/icon/ico_Leona.jpg', 
                        'image/icon/ico_Lillia.jpg', 
                        'image/icon/ico_Lissandra.jpg', 
                        'image/icon/ico_Lucian.jpg', 
                        'image/icon/ico_Lulu.jpg', 
                        'image/icon/ico_Lux.jpg', 
                        'image/icon/ico_Malphite.jpg', 
                        'image/icon/ico_Malzahar.jpg', 
                        'image/icon/ico_Maokai.jpg', 
                        'image/icon/ico_Masteryi.jpg', 
                        'image/icon/ico_MissFortune.jpg', 
                        'image/icon/ico_MonkeyKing.jpg', 
                        'image/icon/ico_Mordekaiser.jpg', 
                        'image/icon/ico_Morgana.jpg', 
                        'image/icon/ico_Nami.jpg', 
                        'image/icon/ico_Nasus.jpg', 
                        'image/icon/ico_Nautilus.jpg', 
                        'image/icon/ico_Neeko.jpg', 
                        'image/icon/ico_Nidalee.jpg', 
                        'image/icon/ico_Nilah.jpg', 
                        'image/icon/ico_Nocturne.jpg', 
                        'image/icon/ico_Nunu.jpg', 
                        'image/icon/ico_Olaf.jpg', 
                        'image/icon/ico_Orianna.jpg', 
                        'image/icon/ico_Ornn.jpg', 
                        'image/icon/ico_Pantheon.jpg', 
                        'image/icon/ico_Poppy.jpg', 
                        'image/icon/ico_Pyke.jpg', 
                        'image/icon/ico_Qiyana.jpg', 
                        'image/icon/ico_Quinn.jpg', 
                        'image/icon/ico_Rakan.jpg', 
                        'image/icon/ico_Rammus.jpg', 
                        'image/icon/ico_RekSai.jpg', 
                        'image/icon/ico_Rell.jpg', 
                        'image/icon/ico_Renekton.jpg', 
                        'image/icon/ico_Rengar.jpg', 
                        'image/icon/ico_Riven.jpg', 
                        'image/icon/ico_Rumble.jpg', 
                        'image/icon/ico_Ryze.jpg', 
                        'image/icon/ico_Samira.jpg', 
                        'image/icon/ico_Sejuani.jpg', 
                        'image/icon/ico_Senna.jpg', 
                        'image/icon/ico_Seraphine.jpg', 
                        'image/icon/ico_Sett.jpg', 
                        'image/icon/ico_Shaco.jpg', 
                        'image/icon/ico_Shen.jpg', 
                        'image/icon/ico_Shyvana.jpg', 
                        'image/icon/ico_Singed.jpg', 
                        'image/icon/ico_Sion.jpg', 
                        'image/icon/ico_Sivir.jpg', 
                        'image/icon/ico_Skarner.jpg', 
                        'image/icon/ico_Sona.jpg', 
                        'image/icon/ico_Soraka.jpg', 
                        'image/icon/ico_Swain.jpg', 
                        'image/icon/ico_Sylas.jpg', 
                        'image/icon/ico_Syndra.jpg', 
                        'image/icon/ico_TahmKench.jpg', 
                        'image/icon/ico_Taliyah.jpg', 
                        'image/icon/ico_Talon.jpg', 
                        'image/icon/ico_Taric.jpg', 
                        'image/icon/ico_Teemo.jpg', 
                        'image/icon/ico_Thresh.jpg', 
                        'image/icon/ico_Tristana.jpg', 
                        'image/icon/ico_Trundle.jpg', 
                        'image/icon/ico_Tryndamere.jpg', 
                        'image/icon/ico_Twistedfate.jpg', 
                        'image/icon/ico_Twitch.jpg', 
                        'image/icon/ico_Udyr.jpg', 
                        'image/icon/ico_Urgot.jpg', 
                        'image/icon/ico_Varus.jpg', 
                        'image/icon/ico_Vayne.jpg', 
                        'image/icon/ico_Veigar.jpg', 
                        'image/icon/ico_VelKoz.jpg', 
                        'image/icon/ico_Vex.jpg', 
                        'image/icon/ico_Vi.jpg', 
                        'image/icon/ico_Viego.jpg', 
                        'image/icon/ico_Viktor.jpg', 
                        'image/icon/ico_Vladimir.jpg', 
                        'image/icon/ico_Volibear.jpg', 
                        'image/icon/ico_Warwick.jpg', 
                        'image/icon/ico_Xayah.jpg', 
                        'image/icon/ico_Xerath.jpg', 
                        'image/icon/ico_Xinzhao.jpg', 
                        'image/icon/ico_Yasuo.jpg', 
                        'image/icon/ico_Yone.jpg', 
                        'image/icon/ico_Yorick.jpg', 
                        'image/icon/ico_Yuumi.jpg', 
                        'image/icon/ico_Zac.jpg', 
                        'image/icon/ico_Zed.jpg', 
                        'image/icon/ico_Zeri.jpg', 
                        'image/icon/ico_Ziggs.jpg', 
                        'image/icon/ico_Zilean.jpg', 
                        'image/icon/ico_Zoe.jpg', 
                        'image/icon/ico_Zyra.jpg', 
                        'image/icon/ico_RenataGlasc.jpg', 
                        'image/icon/ico_Aatrox.jpg'
                        ];

const AC_GChampionSrc = ['image/g_icon/ico_Ahri.png', 
                         'image/g_icon/ico_Akali.png', 
                         'image/g_icon/ico_Akshan.png', 
                         'image/g_icon/ico_Alistar.png', 
                         'image/g_icon/ico_Amumu.png', 
                         'image/g_icon/ico_Anivia.png', 
                         'image/g_icon/ico_Annie.png', 
                         'image/g_icon/ico_Aphelios.png', 
                         'image/g_icon/ico_Ashe.png', 
                         'image/g_icon/ico_AurelionSol.png', 
                         'image/g_icon/ico_Azir.png', 
                         'image/g_icon/ico_Bard.png', 
                         'image/g_icon/ico_BelVeth.png', 
                         'image/g_icon/ico_Blitzcrank.png', 
                         'image/g_icon/ico_Brand.png', 
                         'image/g_icon/ico_Braum.png', 
                         'image/g_icon/ico_Caitlyn.png', 
                         'image/g_icon/ico_Camille.png', 
                         'image/g_icon/ico_Cassiopeia.png', 
                         'image/g_icon/ico_Chogath.png', 
                         'image/g_icon/ico_Corki.png', 
                         'image/g_icon/ico_Darius.png', 
                         'image/g_icon/ico_Diana.png', 
                         'image/g_icon/ico_Draven.png', 
                         'image/g_icon/ico_Drmundo.png', 
                         'image/g_icon/ico_Ekko.png', 
                         'image/g_icon/ico_Elise.png', 
                         'image/g_icon/ico_Evelynn.png', 
                         'image/g_icon/ico_Ezreal.png', 
                         'image/g_icon/ico_Fiddlesticks.png', 
                         'image/g_icon/ico_Fiora.png', 
                         'image/g_icon/ico_Fizz.png', 
                         'image/g_icon/ico_Galio.png', 
                         'image/g_icon/ico_Gangplank.png', 
                         'image/g_icon/ico_Garen.png', 
                         'image/g_icon/ico_Gnar.png', 
                         'image/g_icon/ico_Gragas.png', 
                         'image/g_icon/ico_Graves.png', 
                         'image/g_icon/ico_Gwen.png', 
                         'image/g_icon/ico_Hecarim.png', 
                         'image/g_icon/ico_Heimerdinger.png', 
                         'image/g_icon/ico_Illaoi.png', 
                         'image/g_icon/ico_Irelia.png', 
                         'image/g_icon/ico_Ivern.png', 
                         'image/g_icon/ico_Janna.png', 
                         'image/g_icon/ico_JarvanIV.png', 
                         'image/g_icon/ico_Jax.png', 
                         'image/g_icon/ico_Jayce.png', 
                         'image/g_icon/ico_Jhin.png', 
                         'image/g_icon/ico_Jinx.png', 
                         'image/g_icon/ico_Kaisa.png', 
                         'image/g_icon/ico_Kalista.png', 
                         'image/g_icon/ico_Karma.png', 
                         'image/g_icon/ico_Karthus.png', 
                         'image/g_icon/ico_Kassadin.png', 
                         'image/g_icon/ico_Katarina.png', 
                         'image/g_icon/ico_Kayle.png', 
                         'image/g_icon/ico_Kayn.png', 
                         'image/g_icon/ico_Kennen.png', 
                         'image/g_icon/ico_KhaZix.png', 
                         'image/g_icon/ico_Kindred.png', 
                         'image/g_icon/ico_Kled.png', 
                         'image/g_icon/ico_KogMaw.png', 
                         'image/g_icon/ico_leblanc.png', 
                         'image/g_icon/ico_LeeSin.png', 
                         'image/g_icon/ico_Leona.png', 
                         'image/g_icon/ico_Lillia.png', 
                         'image/g_icon/ico_Lissandra.png', 
                         'image/g_icon/ico_Lucian.png', 
                         'image/g_icon/ico_Lulu.png', 
                         'image/g_icon/ico_Lux.png', 
                         'image/g_icon/ico_Malphite.png', 
                         'image/g_icon/ico_Malzahar.png', 
                         'image/g_icon/ico_Maokai.png', 
                         'image/g_icon/ico_Masteryi.png', 
                         'image/g_icon/ico_MissFortune.png', 
                         'image/g_icon/ico_MonkeyKing.png', 
                         'image/g_icon/ico_Mordekaiser.png', 
                         'image/g_icon/ico_Morgana.png', 
                         'image/g_icon/ico_Nami.png', 
                         'image/g_icon/ico_Nasus.png', 
                         'image/g_icon/ico_Nautilus.png', 
                         'image/g_icon/ico_Neeko.png', 
                         'image/g_icon/ico_Nidalee.png', 
                         'image/g_icon/ico_Nilah.png', 
                         'image/g_icon/ico_Nocturne.png', 
                         'image/g_icon/ico_Nunu.png', 
                         'image/g_icon/ico_Olaf.png', 
                         'image/g_icon/ico_Orianna.png', 
                         'image/g_icon/ico_Ornn.png', 
                         'image/g_icon/ico_Pantheon.png', 
                         'image/g_icon/ico_Poppy.png', 
                         'image/g_icon/ico_Pyke.png', 
                         'image/g_icon/ico_Qiyana.png', 
                         'image/g_icon/ico_Quinn.png', 
                         'image/g_icon/ico_Rakan.png', 
                         'image/g_icon/ico_Rammus.png', 
                         'image/g_icon/ico_RekSai.png', 
                         'image/g_icon/ico_Rell.png', 
                         'image/g_icon/ico_Renekton.png', 
                         'image/g_icon/ico_Rengar.png', 
                         'image/g_icon/ico_Riven.png', 
                         'image/g_icon/ico_Rumble.png', 
                         'image/g_icon/ico_Ryze.png', 
                         'image/g_icon/ico_Samira.png', 
                         'image/g_icon/ico_Sejuani.png', 
                         'image/g_icon/ico_Senna.png', 
                         'image/g_icon/ico_Seraphine.png', 
                         'image/g_icon/ico_Sett.png', 
                         'image/g_icon/ico_Shaco.png', 
                         'image/g_icon/ico_Shen.png', 
                         'image/g_icon/ico_Shyvana.png', 
                         'image/g_icon/ico_Singed.png', 
                         'image/g_icon/ico_Sion.png', 
                         'image/g_icon/ico_Sivir.png', 
                         'image/g_icon/ico_Skarner.png', 
                         'image/g_icon/ico_Sona.png', 
                         'image/g_icon/ico_Soraka.png', 
                         'image/g_icon/ico_Swain.png', 
                         'image/g_icon/ico_Sylas.png', 
                         'image/g_icon/ico_Syndra.png', 
                         'image/g_icon/ico_TahmKench.png', 
                         'image/g_icon/ico_Taliyah.png', 
                         'image/g_icon/ico_Talon.png', 
                         'image/g_icon/ico_Taric.png', 
                         'image/g_icon/ico_Teemo.png', 
                         'image/g_icon/ico_Thresh.png', 
                         'image/g_icon/ico_Tristana.png', 
                         'image/g_icon/ico_Trundle.png', 
                         'image/g_icon/ico_Tryndamere.png', 
                         'image/g_icon/ico_Twistedfate.png', 
                         'image/g_icon/ico_Twitch.png', 
                         'image/g_icon/ico_Udyr.png', 
                         'image/g_icon/ico_Urgot.png', 
                         'image/g_icon/ico_Varus.png', 
                         'image/g_icon/ico_Vayne.png', 
                         'image/g_icon/ico_Veigar.png', 
                         'image/g_icon/ico_VelKoz.png', 
                         'image/g_icon/ico_Vex.png', 
                         'image/g_icon/ico_Vi.png', 
                         'image/g_icon/ico_Viego.png', 
                         'image/g_icon/ico_Viktor.png', 
                         'image/g_icon/ico_Vladimir.png', 
                         'image/g_icon/ico_Volibear.png', 
                         'image/g_icon/ico_Warwick.png', 
                         'image/g_icon/ico_Xayah.png', 
                         'image/g_icon/ico_Xerath.png', 
                         'image/g_icon/ico_Xinzhao.png', 
                         'image/g_icon/ico_Yasuo.png', 
                         'image/g_icon/ico_Yone.png', 
                         'image/g_icon/ico_Yorick.png', 
                         'image/g_icon/ico_Yuumi.png', 
                         'image/g_icon/ico_Zac.png', 
                         'image/g_icon/ico_Zed.png', 
                         'image/g_icon/ico_Zeri.png', 
                         'image/g_icon/ico_Ziggs.png', 
                         'image/g_icon/ico_Zilean.png', 
                         'image/g_icon/ico_Zoe.png', 
                         'image/g_icon/ico_Zyra.png', 
                         'image/g_icon/ico_RenataGlasc.png', 
                         'image/g_icon/ico_Aatrox.png'
                         ];

let AL_table = document.getElementById('mytable');

//リロールボタン
document.getElementsByTagName('button')[0].addEventListener('click', () => {
  let AL_random = [];

  //テーブルの行列分繰り返し
  for (let row of AL_table.rows) {
    for (let cell of row.cells) {
      let L_frag = 0;

      do {
        let L_random = getRandomInt(0, AC_ChampionImageTag.length);
        let L_index = 0;
        L_frag = 0;

        //重複排除
        while (L_index < AL_random.length) {
          if (L_random == AL_random[L_index]) {
            L_frag = 1;
          }
          L_index++;
        }

        //ランダムなアイコンをテーブルに差し替え
        if (L_frag == 0) {
          cell.innerHTML = AC_ChampionImageTag[L_random];
          AL_random[AL_random.length] = L_random;
        }
      } while (L_frag == 1);
    }
  }
});

//乱数
function getRandomInt(min, max) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min) + min); //The maximum is exclusive and the minimum is inclusive
}

//アイコンをクリックすると通常とグレースケールを入れ替える
function reimage(c_number) {
  let c_image = document.getElementById(c_number);

  if (c_image.src.match(/g_/)) {
    c_image.src = AC_ChampionSrc[c_number];
  } else {
    c_image.src = AC_GChampionSrc[c_number];
  }
}
